#[http]
#proxy = "127.0.0.1:7890"
#[https]
#proxy = "127.0.0.1:7890"
[net]
git-fetch-with-cli=true

[build]
rustc-wrapper = "sccache"
incremental = true
rustflags = [
"-Ctarget-cpu=native",
"-Clink-arg=-fuse-ld=mold"]

[profile.dev]
codegen-backend = "cranelift"
debug = false
opt-level = 1

[profile.dev.package."*"]
codegen-backend = "llvm"
opt-level = 3

[profile.release]
debug=true
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"

[unstable]
codegen-backend = true
