#[http]
#proxy = "127.0.0.1:7890"

#[https]
#proxy = "127.0.0.1:7890"
[net]
git-fetch-with-cli=true

[build]
rustc-wrapper = "sccache"
incremental = true 

[profile.dev]
opt-level = 0  # Controls the --opt-level the compiler builds with
debug = true   # Controls whether the compiler passes `-g`

[profile.release]
debug=true
[target.x86_64-unknown-linux-gnu]

rustflags = [
   "-Clinker=clang",
   "-Clink-arg=-fuse-ld=/bin/mold"]

